### PR TITLE
Ensure colons do not break titles

### LINKED ISSUE #38: jekyll post creates invalid YAML header for title with colon
Adding a new post with a title containing colon leads to a failed build.
Example:
`jekyll post "My new post : Part 1"`
YAML spec requires to put a text string with colons into quotes.
See [this issue](https://github.com/jekyll/jekyll/issues/1011) for details.

### PR DESCRIPTION
**Pull request by djds23**
When titles have colons in them, it breaks the liquid template.
This encapsulates the titles in string literals if the user
wants a title with a colon in it.

Closes #38

### CODE REVIEW

File: lib/jekyll-compose/file_info.rb [hunk 1]
```diff
@@ -13,8 +13,18 @@ def content
     <<-CONTENT.gsub /^\s+/, ''
       ---
       layout: #{params.layout}
-      title: #{params.title}
+      title: #{yaml_clean_title}
```
Comment (parkr) [inline lib/jekyll-compose/file_info.rb]: Do you think we could do this instead?

```ruby
YAML.dump({
  "layout" => params.layout,
  "title" => params.title
})
```

Comment (djds23) [inline lib/jekyll-compose/file_info.rb]: That is a far more elegant solution! thanks for the tip.

**Comment by djds23** [comment]
@parkr it looks like using `YAML#dump` breaks support for >2.0 versions of ruby. Would you prefer I put   logic to check the ruby runtime and use my previous method for versions >2.0? Or would you like to break support for >1.9 in the next release?

Thanks again for taking time with my PR.

**Comment by djds23** [comment]
Apparently in ruby 1.9, the string is interpreted as [a non-specific tag](http://yaml.org/spec/1.2/spec.html#id2785512 ).

**Comment by djds23** [comment]
@parkr since the non-specific tag is still valid YAML, I just updated the spec to only ensure that the title is wrapped in quotes, not check that the syntax is exactly the same.

**Comment by parkr** [comment]
> Or would you like to break support for >1.9 in the next release?

Let's remove support for v1.9. We don't support it in Jekyll and it's EOL'd so I'm fine with this. Would you ensure you get the correct title in the YAML and that it parses properly? Thanks!

**Comment by djds23** [comment]
@parkr I reverted the tests so they test for the exact string. This breaks tests on >1.9, but is better coverage. I think this is ready to :ship: !

**Comment by parkr** [comment]
@jekyllbot: merge
